version: '3.8'

services:
  server:
    build: ./server
    container_name: traveltales-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=traveltales_secret_key
    restart: unless-stopped

  client:
    build: ./client
    container_name: traveltales-client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped 