version: '3.8'

services:
  server:
    build: ./server
    container_name: traveltales-server
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - JWT_SECRET=jwt_secret_key
    restart: unless-stopped

  client:
    build: ./client
    container_name: traveltales-client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped 